# This is an ansible-playbook to launch firefox inside the docker container
# The docker host where our playbook will run is named conatiner and the dns is already setup
# The firsr step is to complete the building of image with the dockerfile
- import_playbook: prerequisites.yml
- hosts: localhost
  tasks:
   - include_vars: var.yml
   - name: "Tar Image"
     docker_image:
       load_path: centos-latest.tar
       name: centos:latest
       state: present
     ignore_errors: yes
   - name: "Using Dockerfile"
     docker_image:
        dockerfile: "Dockerfile_firefox"
        name: cfire:v1
        pull: no
        path: /root/firefox/
        state: present
   - name: "Docker Containter"
     docker_container: 
       interactive: yes
       tty: yes
       image: cfire:v1
       name: cf1
       env:
         DISPLAY: ":0"
       volumes: 
        - /tmp/.X11-unix:/tmp/.X11-unix:rw


